In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(np.ndim(A)) # 배열의 차원 수
print(A.shape)
print(A.shape[0]) # 열 * 행

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
3


In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
print(np.dot(A, B)) # 행렬 곱셈

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
