In [1]:
import numpy as np

In [6]:
# 배열 생성
x = np.array([1, 2, 3])
print(x)
print(x.shape)
print(type(x))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [ ]:
# N 배열 생성
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print(type(x))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [14]:
# 산술 연산
# 배열의 각 원소에 대해 연산을 수산
# 원소 수 다르면 오류 발생
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print("x: ", x)
print("y: ", y)
print("x + y: ", x + y)
print("x - y: ", x - y)
print("x * y: ", x * y)
print("x / y: ", x / y)

x:  [1. 2. 3.]
y:  [2. 4. 6.]
x + y:  [3. 6. 9.]
x - y:  [-1. -2. -3.]
x * y:  [ 2.  8. 18.]
x / y:  [0.5 0.5 0.5]


In [16]:
# 브로드캐스트
# 배열의 크기가 다를 때 작은 배열을 큰 배열에 맞춰서 연산
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[10, 20, 30]])
print("A: ", A)
print("B: ", B)
print("A + B: ", A + B)

A:  [[1 2 3]
 [4 5 6]]
B:  [[10 20 30]]
A + B:  [[11 22 33]
 [14 25 36]]


In [ ]:
# 원소 접근 index
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x[0])  # 첫 번째 행
print(x[0][0])  # 첫 번째 행, 첫 번째 열

[[1 2 3]
 [4 5 6]]
[1 2 3]
1


In [20]:
# 원소 접근 for
# 행렬의 차원 접근
for row in x:
    print(row)
# 행렬의 원소 접근
for row in x:
    for col in row:
        print(col)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [23]:
# 행렬의 평탄화
x = x.flatten()
print(x)
x = np.array([1, 2, 3, 4, 5, 6])
# 인덱스 0, 2, 4인 원소 얻기
print(x[[0, 2, 4]])
# 인덱스 0, 2, 4인 원소의 합
print("원소 합: ", np.sum(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 평균
print("원소 평균: ", np.mean(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 최대값
print("원소 최대값: ", np.max(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 최소값
print("원소 최소값: ", np.min(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 표준편차
print("원소 표준편차: ", np.std(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 분산
print("원소 분산: ", np.var(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 중앙값
print("원소 중앙값: ", np.median(x[[0, 2, 4]]))
# 인덱스 0, 2, 4인 원소의 사분위수
print("원소 1사분위수: ", np.percentile(x[[0, 2, 4]], 25))  # 1사분위수
print("원소 2사분위수: ", np.percentile(x[[0, 2, 4]], 50))  # 2사분위수
print("원소 3사분위수: ", np.percentile(x[[0, 2, 4]], 75))  # 3사분위수

[1 2 3 4 5 6]
[1 3 5]
원소 합:  9
원소 평균:  3.0
원소 최대값:  5
원소 최소값:  1
원소 표준편차:  1.632993161855452
원소 분산:  2.6666666666666665
원소 중앙값:  3.0
원소 1사분위수:  2.0
원소 2사분위수:  3.0
원소 3사분위수:  4.0
